---
# tasks file for deploy_nginx
- name: 'Add epel-release repo'
  yum:
    name: epel-release
    state: present

- name: 'Install nginx'
  yum:
    name: nginx
    state: present
  notify:
  - restart nginx
  tags:
  - nginx-package
  - package

- name: 'Create NGINX config file from template'
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
  - reload nginx
  tags:
  - nginx-configuration